name: Build and Deploy Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      # Gradle 캐시 추가
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: gradlew 권한 부여
        run: chmod +x ./gradlew

      - name: gradle build
        run: ./gradlew build

      - name: build를 서버로 이동
        run: |
          rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./build/libs/ \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/ubuntu/orchid-aiot-spring/build/libs

      - name: 서버에 접속해 docker-compose 재시작
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd /home/ubuntu/orchid-aiot-spring
            docker-compose down
            docker-compose up -d --build
          EOF
