name: Deploy Spring Boot to OCI Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gradle 캐시 추가
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # gradlew 실행 권한
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 테스트 생략한 빌드
      - name: Gradle bootJar build (no test)
        run: ./gradlew bootJar

      # SSH 설정
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 서버 접속 및 배포
      - name: Deploy to OCI Server
        run: |
          ssh -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -o StrictHostKeyChecking=no ubuntu@${{ secrets.SSH_HOST }} '
            cd ~/orchid-aiot-spring && 
            git pull origin main && 
            docker compose down && 
            docker compose up -d --build
          '
